### ISSUE TITLE
Logo proposal for BookShelf

### ISSUE THREAD

**Issue by zuurw** [Nevenall/bookshelf#2]
Hi, my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by Nevenall** [comment]
Hi Zuur!
I would definitely be interested. Thank you!

**Comment by zuurw** [comment]
Hi @Nevenall, do you have any request or any idea from what you want? Can you give me something to get inspired?

Best Regards!

**Comment by Nevenall** [comment]
Yes, I definitely have some thoughts. 
[This](https://github.com/Nevenall/BookShelf/blob/master/src/assets/logo.png) is the existing logo I did from http://game-icons.net/ 
BookShelf is intended to be used for multiple books, each with its own custom style, so some indicator of multiplicity would be cool. As would a logo friendly to having it's color changed to match a particular book's theme. Or match a book's theme in some other way. :)
Ideally, I'd like something that looks identifiable and nice at smaller sizes like 32x32px. 

Hope that helps!

**Comment by zuurw** [comment]
Hi @Nevenall, here is my design for BookShelf, I create something simple and easy to remember and I think it works good on smaller sizes.

First I create the logo just for one color, but I add also a two color logo.

Send me your feedback.

Best Regards!

![logo proposal1](https://user-images.githubusercontent.com/40801473/43196095-c9a65c56-8ffe-11e8-82fd-b3e982b69bb4.png)

**Comment by Nevenall** [comment]
Cool! I like that!

**Comment by zuurw** [comment]
Hi @Nevenall, Im happy that you like it.
What color do you want for the logo? after you decide I will create a pull request with the files.

Best Regards!

**Comment by zuurw** [comment]
Hi @Nevenall can I make the pull request?

Best Regards!

**Comment by Nevenall** [comment]
Yes, sorry! 
Hard to decide on a color!
Lets do orange. 

Thank you so much!
Dan.

**Comment by zuurw** [comment]
Hi @Nevenall, I create the PR with logo design files and I put also the logo on the README and It looks really good.

Best Regards!

**Comment by Nevenall** [comment]
Nice! 
I'd like to add an attribution in the readme for you. 
Do you have a link you'd like me to use?

**Comment by zuurw** [comment]
Hi @Nevenall, here is the link https://github.com/zuurw/Graphic-Design-

Do you have other projects to work, that need a logo?

Best Regards!

**Comment by Nevenall** [comment]
In the near future I am going to be working on an app for a friend to track student achievements. I'll ping you when I get started. 
Thanks again!
